version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  migration_runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - back_net
    environment:
      DATABASE_URL: postgresql://postgres:root123@db:5432/app_db
    command: alembic upgrade head
    restart: "no"

  seed_runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    working_dir: /app/src
    depends_on:
      migration_runner:
        condition: service_completed_successfully
    networks:
      - back_net
    volumes:
      - ./seed_output/:/app/src/seed/output
    environment:
      DATABASE_URL: postgresql://postgres:root123@db:5432/app_db
    command: python -m seed.run_seed
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    working_dir: /app/src
    depends_on:
      seed_runner:
        condition: service_completed_successfully
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
    networks:
      - front_net
      - back_net
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - front_net

networks:
  front_net:
  back_net:

volumes:
  db_data:
  nginx_logs:
  seed_output:
